ARG ELK_VERSION

# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}

#RUN curl -XPUT -u elastic:changeme http://elasticsearch:9200/_template/snslog -H 'Content-Type: application/json' -d @/usr/share/elasticsearch/templates/sns.template.json
#RUN curl -XPUT -u elastic:changeme http://elasticsearch:9200/_template/sdmclog -H 'Content-Type: application/json' -d @/usr/share/elasticsearch/templates/sdmc.template.json
#RUN curl -XPUT -u elastic:changeme http://elasticsearch:9200/_template/sdslog -H 'Content-Type: application/json' -d @/usr/share/elasticsearch/templates/sds.template.json
#RUN curl -XPUT -u elastic:changeme http://elasticsearch:9200/_template/seslog -H 'Content-Type: application/json' -d @/usr/share/elasticsearch/templates/ses.template.json
